spring.application.name=lost-found-backend

spring.datasource.url=jdbc:mysql://localhost:3306/lost_found_db
spring.datasource.username=root
spring.datasource.password=a34862@TKRS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080